### ISSUE TITLE
"manifold_script_path" not found

### ISSUE THREAD

**Issue by miaoqiz** [ranahanocka/point2mesh#16]
Hi,

Thank you for the excellent framework.

Running "bash ./scripts/examples/giraffe.sh" and got the error below when it gets to "1000" iteration:

----------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "main.py", line 85, in <module>
    mesh = utils.manifold_upsample(mesh, opts.save_path, Mesh,
  File "point2mesh/utils.py", line 18, in manifold_upsample
    raise FileNotFoundError(f'{manifold_script_path} not found')
FileNotFoundError: ~/code/Manifold/build/manifold not found

----------------------------------------------------------------------------------------

Any advise is appreciated!

Thanks so much and have a good day!

**Comment by ranahanocka** [comment]
Hi @miaoqiz --

Did you install the manifold software if so where did you install it?
If it is in a different location than `~/code/Manifold/build/manifold`
Then you should change line 6 in options.py to be the full path of the manifold/build location

**Comment by d289760860** [comment]
I met the same problem. 
Maybe you can try to change

MANIFOLD_DIR = r'~/code/Manifold/build'
in options.py to

MANIFOLD_DIR = r'/home/USER/code/Manifold/build'
(change USER to your user name)

**Comment by maque-hub** [comment]
I met the same problem. You could try to change

> if not os.path.exists(manifold_script_path):

in utils.py to
 
> if not os.path.exists(MANIFOLD_DIR):

This worked for me. Getting this error means that "/code/Manifold/build/manifold" is not a path. If you did install manifold in "/code/Manifold/build", you could remove 'manifold' and retry.

**Comment by cxy747254545** [comment]
hello ,I met the same problem. then,i changed line 6 in options.py to be the full path of the manifold/build location：

`MANIFOLD_DIR = 'F:\\point2mesh\\point2mesh\\code\\Manifold\\build'`

I use Windows system。Running "main.py" and got the error below when it gets to "1000" iteration:

'F:\point2mesh\point2mesh\code\Manifold\build\manifold' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'F:\point2mesh\point2mesh\code\Manifold\build\simplify' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "F:/point2mesh/point2mesh/main.py", line 85, in <module>
    mesh = utils.manifold_upsample(mesh, opts.save_path, Mesh,
  File "F:\point2mesh\point2mesh\utils.py", line 27, in manifold_upsample
    m_out = Mesh(temp_file, hold_history=True, device=mesh.device)
  File "F:\point2mesh\point2mesh\models\layers\mesh.py", line 24, in __init__
    self.vs, self.faces = load_obj(file)
  File "F:\point2mesh\point2mesh\utils.py", line 59, in load_obj
    f = open(file)
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/guitar\\tempdcb80901-3103-45eb-9bfa-c0f2fbfa0381.obj'

**Comment by zgc1135147247** [comment]
hi,I use windows  systems.how to install 

> hello ,I met the same problem. then,i changed line 6 in options.py to be the full path of the manifold/build location：
> 
> `MANIFOLD_DIR = 'F:\\point2mesh\\point2mesh\\code\\Manifold\\build'`
> 
> I use Windows system。Running "main.py" and got the error below when it gets to "1000" iteration:
> 
> 'F:\point2mesh\point2mesh\code\Manifold\build\manifold' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
> ���������ļ���
> 'F:\point2mesh\point2mesh\code\Manifold\build\simplify' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
> ���������ļ���
> Traceback (most recent call last):
> File "F:/point2mesh/point2mesh/main.py", line 85, in
> mesh = utils.manifold_upsample(mesh, opts.save_path, Mesh,
> File "F:\point2mesh\point2mesh\utils.py", line 27, in manifold_upsample
> m_out = Mesh(temp_file, hold_history=True, device=mesh.device)
> File "F:\point2mesh\point2mesh\models\layers\mesh.py", line 24, in **init**
> self.vs, self.faces = load_obj(file)
> File "F:\point2mesh\point2mesh\utils.py", line 59, in load_obj
> f = open(file)
> FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/guitar\tempdcb80901-3103-45eb-9bfa-c0f2fbfa0381.obj'

hi,I also use windows system.did you solute the problem? I cannot run it with the same problem
