### ISSUE TITLE
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by hhf-hd** [ranahanocka/point2mesh#4]
I have encountered such a mistake：

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from models.losses import chamfer_distance
  File "/home/lab505/gpu_point2mesh/models/losses.py", line 3, in <module>
    from pytorch3d.structures.pointclouds import Pointclouds
  File "/home/lab505/anaconda3/envs/p2m/lib/python3.8/site-packages/pytorch3d/structures/__init__.py", line 4, in <module>
    from .pointclouds import Pointclouds
  File "/home/lab505/anaconda3/envs/p2m/lib/python3.8/site-packages/pytorch3d/structures/pointclouds.py", line 5, in <module>
    from .. import ops
  File "/home/lab505/anaconda3/envs/p2m/lib/python3.8/site-packages/pytorch3d/ops/__init__.py", line 5, in <module>
    from .graph_conv import GraphConv
  File "/home/lab505/anaconda3/envs/p2m/lib/python3.8/site-packages/pytorch3d/ops/graph_conv.py", line 6, in <module>
    from pytorch3d import _C
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

here is my configure:
cudatoolkit               10.1.243
pytorch                   1.4.0           py3.8_cuda10.1.243_cudnn7.6.3_0   
pytorch3d                 0.2.0          

but after i use another configure :
pytorch                   1.5.0               py3.8_cpu_0  [cpuonly]  
pytorch3d                 0.2.0                    pypi_0    
it works,but it's too slow ,so i wonder if your code are running on GPU?
look forword to your help,thanks ！

**Comment by RaoHaocheng** [comment]
Hello, 
I have run this code too. if It uses CPU, it can work. However, if I use GPU, it can't work. I install the cuda 10.1. And I found that if my pytorch.cuda.is_available() is Ture, I can't import pytorch3D. If I reinstall pytorch3D, my pytorch.cuda.is_available() is False.    
![image](https://user-images.githubusercontent.com/11450518/83348806-5d8f0d00-a362-11ea-879d-7f2f7e56b506.png)
![image](https://user-images.githubusercontent.com/11450518/83348848-a5ae2f80-a362-11ea-9b0e-0c49689f15d9.png)
![image](https://user-images.githubusercontent.com/11450518/83348862-c24a6780-a362-11ea-88ff-b18a098173d4.png)

**Comment by RaoHaocheng** [comment]
![image](https://user-images.githubusercontent.com/11450518/83348981-a1cedd00-a363-11ea-92f1-48358948f7aa.png)

**Comment by ranahanocka** [comment]
Hi @RaoHaocheng ,

So it seems the issue is with the pytorch3D installation (there is no cuda...). Are you using a windows machine? Maybe you can try the steps listed here: https://github.com/facebookresearch/pytorch3d/issues/172#issuecomment-620855810

**Comment by ranahanocka** [comment]
@RaoHaocheng Also, you might want to try with PyTorch 1.4 instead of 1.5 (it seems that 1.5 might require cuda 10.2?). Did you try installation from the conda env like written in the README?

**Comment by RaoHaocheng** [comment]
@ranahanocka, Thanks for you. I have run it successfully on GPUs. I found that the problem caused by CUDA on the system. My CUDA on the system is 9.2. However, my CUDA on the Conda is 10.1, which causes pytorch3d can't run. So I change the CUDA on the Conda to 9.2. And I install Pytorch3d of CUDA 9.2, which can be found in https://anaconda.org/pytorch3d/pytorch3d/files. So my config is 
![image](https://user-images.githubusercontent.com/11450518/83369945-75ad6d80-a3f0-11ea-9d8e-43d0093f111c.png)
![Uploading image.png…]()
Screenshot of successful running：
![image](https://user-images.githubusercontent.com/11450518/83369488-17cc5600-a3ef-11ea-80fb-39e1cbc8a587.png)

**Comment by RaoHaocheng** [comment]
![image](https://user-images.githubusercontent.com/11450518/83370145-169c2880-a3f1-11ea-8117-2450e07ef3e4.png)

![image](https://user-images.githubusercontent.com/11450518/83370134-0e43ed80-a3f1-11ea-8f49-13bbdec25483.png)

![image](https://user-images.githubusercontent.com/11450518/83370122-04ba8580-a3f1-11ea-92f1-1c7df9bb4762.png)

**Comment by hhf-hd** [comment]
thanks for you reply! 
this is  a impressive work~
i  wonder if your had compared your method with other method such as Poisson reconstruction on a ideal pointcloud set,and what's your maximum resolutions of mesh and the maximum number of pointcloud that your have dealt with ,since when i set max-faces as 100000,it will run out of GPU memory with a  1080Ti when faces is about 30000
look forword to your reply！

**Comment by ranahanocka** [comment]
Hi @hhf-hd ,

Yes, we did compare to Poisson reconstruction (you can see the details in the paper). In general, Poisson reconstruct'











]'

**Comment by ranahanocka** [comment]
Hi @hhf-hd ,

Yes, we did compare to Poisson reconstruction (you can see the details in the paper). In general, Poisson reconstruction is probably the most common technique for surface reconstruction, which incorporates some type of smoothness prior. In theory, a large number of faces is possible, but will require splitting the mesh into more than 8 parts. I think the largest we tried was 80k faces. 
If you are running out of memory, you can increase the # of parts here https://github.com/ranahanocka/point2mesh/blob/c56d89b993efc625c6e8c74040f974bdfe0d5127/options.py#L70

**Comment by xufengfan96** [comment]
Hi,@ranahanocka.
Your work is great and I try to make it. But I meet the same problem about the gpu memory.I want to know the parameters about your GPU.And one more thing I noticed that in the chapter 5.You compared the model with noisy ,inaccurate normals and low density completion in poisson and yours.It really work well in real scan.But how about using a pointcloud set with accuracate normals and uniform x,y,z  coordinate?
