### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by ForrestPi** [ranahanocka/point2mesh#42]
bash ./scripts/examples/giraffe.sh

File "/home/code/point2mesh/models/layers/mesh.py", line 91, in build_gemm
    self.vei = torch.from_numpy(np.concatenate(np.array(self.vei)).ravel()).to(self.device).long()
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2502,) + inhomogeneous part.

**Comment by lazib28** [comment]
hi which version of pytorch, torchvision and pytorch3d did you use?

**Comment by lazib28** [comment]
i am facing the same error, were u able to fix it? 

"$ bash ./scripts/examples/noisy_guitar.sh
device: cpu
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    mesh = Mesh(opts.initial_mesh, device=device, hold_history=True)
  File "C:\point2meshx\point2mesh\models\layers\mesh.py", line 28, in __init__
    self.build_gemm()
  File "C:\point2meshx\point2mesh\models\layers\mesh.py", line 91, in build_gemm
    self.vei = torch.from_numpy(np.concatenate(np.array(self.vei)).ravel()).to(self.device).long()
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (1628,) + inhomogeneous part."

**Comment by lazib28** [comment]
https://github.com/ranahanocka/point2mesh/issues/39#issuecomment-1803804429

was able to fix it. This is the solution ^
